### ISSUE TITLE
Tool crashes using the xlsx files in the repo. "Invalid day or month value".

### ISSUE THREAD

**Issue by jonasfroeller** [Stevan06v/webuntis-excel-reformatter-tool#1]
```bat
C:\Users\Jonas\Downloads\webuntis-excel-reformatting-tool-main>py webuntis-reformatting-tool.py
No file selected.
Restarting...
XLS file selected...
File "C:/Users/Jonas/Downloads/webuntis-excel-reformatting-tool-main/main.xlsx" has been converted to "C:/Users/Jonas/Downloads/webuntis-excel-reformatting-tool-main/temp-webuntis-reformatting-tool-file.xlsx" successfully.
Traceback (most recent call last):
  File "C:\Users\Jonas\Downloads\webuntis-excel-reformatting-tool-main\webuntis-reformatting-tool.py", line 160, in <module>
    assignment_list.append(Assignment(_subject, _day, _month, _type))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonas\Downloads\webuntis-excel-reformatting-tool-main\webuntis-reformatting-tool.py", line 15, in __init__
    self.date = self.create_date_of_month_day(_day, _month)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Jonas\Downloads\webuntis-excel-reformatting-tool-main\webuntis-reformatting-tool.py", line 19, in create_date_of_month_day
    raise ValueError("Invalid day or month value")
ValueError: Invalid day or month value
```

**Comment by jonasfroeller** [comment]
Thank you! :)
